// src/components/ChatArea.jsx
import { COLORS, SIZES } from '../constants'

/**
 * 聊天区域组件
 */
const ChatArea = ({ messages, isChatMode, children, onDragOver, onDragLeave, onDrop }) => {
  return (
    <div
      style={{
        flex: 1,
        overflow: 'auto',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        padding: `${SIZES.spacing.xxl} ${SIZES.spacing.xl} 200px`,
        maxWidth: '1200px',
        margin: '0 auto',
        width: '100%'
      }}
      onDragOver={onDragOver}
      onDragLeave={onDragLeave}
      onDrop={onDrop}
    >
      {!isChatMode ? (
        <>
          <h1 style={{ fontSize: '48px', fontWeight: '600', color: COLORS.text, margin: `${SIZES.spacing.xxl} 0 ${SIZES.spacing.xl}` }}>Hi，</h1>
          <div style={{ width: '100%', height: '1px', backgroundColor: COLORS.border, marginBottom: '32px' }}></div>
          {children}
        </>
      ) : (
        <div style={{ width: '100%', maxWidth: '800px', display: 'flex', flexDirection: 'column', gap: SIZES.spacing.lg }}>
          {messages.map((message, index) => (
            <div
              key={index}
              style={{
                display: 'flex',
                gap: SIZES.spacing.md,
                alignItems: 'flex-start',
                flexDirection: message.role === 'user' ? 'row-reverse' : 'row'
              }}
            >
              <div style={{
                width: '32px',
                height: '32px',
                borderRadius: '50%',
                flexShrink: 0,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                color: COLORS.white,
                fontSize: '12px',
                fontWeight: 500,
                background: message.role === 'user'
                  ? COLORS.primary
                  : `linear-gradient(135deg, ${COLORS.primary} 0%, ${COLORS.primaryDark} 100%)`
              }}>
                {message.role === 'user' ? '我' : '元'}
              </div>
              <div style={{
                maxWidth: '70%',
                borderRadius: SIZES.borderRadius.lg,
                padding: `${SIZES.spacing.md} ${SIZES.spacing.lg}`,
                fontSize: '14px',
                lineHeight: '1.6',
                wordWrap: 'break-word',
                whiteSpace: 'pre-wrap',
                background: message.role === 'user' ? COLORS.primary : COLORS.background,
                color: message.role === 'user' ? COLORS.white : COLORS.text,
                border: message.role === 'user' ? 'none' : `1px solid ${COLORS.border}`
              }}>
                {message.content}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

export default ChatArea

// src/components/ChatArea.vue
<template>
  <div
    class="chat-area"
    @dragover="onDragOver"
    @dragleave="onDragLeave"
    @drop="onDrop"
  >
    <template v-if="!isChatMode">
      <h1 class="greeting">Hi，</h1>
      <div class="divider"></div>
      <slot />
    </template>
    <template v-else>
      <div class="messages">
        <div
          v-for="(message, index) in messages"
          :key="index"
          :class="['message-item', { 'user-message': message.role === 'user' }]"
        >
          <div :class="['avatar', { 'user-avatar': message.role === 'user' }]">
            {{ message.role === 'user' ? '我' : '元' }}
          </div>
          <div :class="['message-content', { 'user-content': message.role === 'user' }]">
            {{ message.content }}
          </div>
        </div>
      </div>
    </template>
  </div>
</template>

<script setup>
defineProps({
  messages: {
    type: Array,
    default: () => []
  },
  isChatMode: {
    type: Boolean,
    default: false
  },
  onDragOver: {
    type: Function,
    default: () => {}
  },
  onDragLeave: {
    type: Function,
    default: () => {}
  },
  onDrop: {
    type: Function,
    default: () => {}
  }
})
</script>

<style scoped>
.chat-area {
  flex: 1;
  overflow: auto;
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 40px 24px 200px;
  max-width: 1200px;
  margin: 0 auto;
  width: 100%;
}

.greeting {
  font-size: 48px;
  font-weight: 600;
  color: #1f2937;
  margin: 40px 0 24px;
}

.divider {
  width: 100%;
  height: 1px;
  background-color: #e5e7eb;
  margin-bottom: 32px;
}

.messages {
  width: 100%;
  max-width: 800px;
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.message-item {
  display: flex;
  gap: 12px;
  align-items: flex-start;
}

.message-item.user-message {
  flex-direction: row-reverse;
}

.avatar {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
  font-size: 12px;
  font-weight: 500;
  background: linear-gradient(135deg, #0066ff 0%, #0052cc 100%);
}

.user-avatar {
  background: #0066ff;
}

.message-content {
  max-width: 70%;
  border-radius: 12px;
  padding: 12px 16px;
  font-size: 14px;
  line-height: 1.6;
  word-wrap: break-word;
  white-space: pre-wrap;
  background: white;
  color: #1f2937;
  border: 1px solid #e5e7eb;
}

.user-content {
  background: #0066ff;
  color: white;
  border: none;
}

/* 移动端响应式 */
@media (max-width: 768px) {
  .chat-area {
    padding: 20px 12px 180px;
  }

  .greeting {
    font-size: 32px;
    margin: 20px 0 16px;
  }

  .divider {
    margin-bottom: 20px;
  }

  .messages {
    gap: 12px;
  }

  .message-item {
    gap: 8px;
  }

  .avatar {
    width: 28px;
    height: 28px;
    font-size: 11px;
  }

  .message-content {
    max-width: 85%;
    padding: 10px 12px;
    font-size: 13px;
    border-radius: 10px;
  }
}
</style>
