// src/App.jsx
import { useState, useRef } from 'react'
import { MODELS, COLORS } from './constants'
import { useDragAndDrop } from './hooks/useDragAndDrop'
import Sidebar from './components/Sidebar'
import Header from './components/Header'
import ChatArea from './components/ChatArea'
import SuggestionCards from './components/SuggestionCards'
import InputArea from './components/InputArea'
import DragOverlay from './components/DragOverlay'

/**
 * 主应用组件
 * 遵循Clean Code原则：单一职责、组件拆分、逻辑分离
 */
function App() {
  // 状态管理
  const [inputValue, setInputValue] = useState('')
  const [messages, setMessages] = useState([])
  const [isChatMode, setIsChatMode] = useState(false)
  const [selectedModel, setSelectedModel] = useState(MODELS.HUNYUAN)
  const textareaRef = useRef(null)

  // 拖拽上传
  const { isDragging, handlers: dragHandlers } = useDragAndDrop((files) => {
    // TODO: 处理文件上传
    console.log('Files dropped:', files)
  })

  // 事件处理函数
  const handleSend = () => {
    if (!inputValue.trim()) return
    
    setIsChatMode(true)
    setMessages([...messages, { role: 'user', content: inputValue }])
    setInputValue('')
    
    if (textareaRef.current) {
      textareaRef.current.value = ''
    }
  }

  const handleExampleClick = (text) => {
    setInputValue(text)
    if (textareaRef.current) {
      textareaRef.current.value = text
    }
    setTimeout(() => handleSend(), 100)
  }

  const handleInputChange = (value) => {
    setInputValue(value)
  }

  return (
    <div style={{
      display: 'flex',
      height: '100vh',
      backgroundColor: COLORS.background
    }}>
      {/* 左侧导航栏 */}
      <Sidebar />

      {/* 主内容区域 */}
      <div style={{
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: COLORS.background,
        position: 'relative',
        overflow: 'hidden'
      }}>
        {/* 顶部栏 */}
        <Header selectedModel={selectedModel} onModelChange={setSelectedModel} />

        {/* 聊天区域 */}
        <ChatArea
          messages={messages}
          isChatMode={isChatMode}
          onDragOver={dragHandlers.onDragOver}
          onDragLeave={dragHandlers.onDragLeave}
          onDrop={dragHandlers.onDrop}
        >
          <SuggestionCards onCardClick={handleExampleClick} />
        </ChatArea>

        {/* 拖拽覆盖层 */}
        <DragOverlay isVisible={isDragging} />

        {/* 输入区域 */}
        <InputArea
          inputValue={inputValue}
          onInputChange={handleInputChange}
          onSend={handleSend}
          textareaRef={textareaRef}
        />
      </div>
    </div>
  )
}

export default App

// src/App.vue
<template>
  <div class="app">
    <!-- 左侧导航栏 -->
    <Sidebar />

    <!-- 主内容区域 -->
    <div class="main-content">
      <!-- 顶部栏 -->
      <Header :selected-model="selectedModel" @update:selected-model="selectedModel = $event" />

      <!-- 聊天区域 -->
      <ChatArea
        :messages="messages"
        :is-chat-mode="isChatMode"
        :on-drag-over="dragHandlers.onDragOver"
        :on-drag-leave="dragHandlers.onDragLeave"
        :on-drop="dragHandlers.onDrop"
      >
        <SuggestionCards @card-click="handleExampleClick" />
      </ChatArea>

      <!-- 拖拽覆盖层 -->
      <DragOverlay :is-visible="isDragging" />

      <!-- 输入区域 -->
      <InputArea v-model="inputValue" @send="handleSend" />
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { MODELS } from './constants'
import { useDragAndDrop } from './composables/useDragAndDrop'
import Sidebar from './components/Sidebar.vue'
import Header from './components/Header.vue'
import ChatArea from './components/ChatArea.vue'
import SuggestionCards from './components/SuggestionCards.vue'
import InputArea from './components/InputArea.vue'
import DragOverlay from './components/DragOverlay.vue'

// 状态管理
const inputValue = ref('')
const messages = ref([])
const isChatMode = ref(false)
const selectedModel = ref(MODELS.MODEL1)

// 拖拽上传
const { isDragging, handlers: dragHandlers } = useDragAndDrop((files) => {
  console.log('Files dropped:', files)
  // TODO: 处理文件上传
})

// 事件处理函数
const handleSend = (text) => {
  if (!text?.trim()) return

  isChatMode.value = true
  messages.value.push({ role: 'user', content: text })
  
  // TODO: 调用AI API获取回复
  setTimeout(() => {
    messages.value.push({ role: 'assistant', content: '这是AI的回复（待接入真实API）' })
  }, 500)
  
  inputValue.value = ''
}

const handleExampleClick = (text) => {
  inputValue.value = text
  setTimeout(() => {
    handleSend(text)
  }, 100)
}
</script>

<style scoped>
.app {
  display: flex;
  height: 100vh;
  background-color: #ffffff;
}

.main-content {
  flex: 1;
  display: flex;
  flex-direction: column;
  background-color: #ffffff;
  position: relative;
  overflow: hidden;
}
</style>
